:wrench: Add toggle
Schneegans/Fly-Pie pull request #214
Opened 2022-03-26 20:13 UTC by GestaltEngine

:wrench: Add ToggleMenu D-Bud method. 
Best used in combination with xbindkeys to open/close menus with a single mouse button.

2022-03-26 20:18 UTC, Schneegans commented
Thanks a lot, I'll test it tomorrow! And sorry that there was still the `develop` branch around. I simplified Fly-Pie's branching scheme with the latest release and totally forgot to delete it :wink:

2022-03-27 05:15 UTC, Schneegans requested changes
Again, thank you very much! I think that this is a small but very useful contribution. I just added two comments which you could directly commit, i think.

Furthermore, it would be cool if you could add a small example of this new method to the [documentation](https://github.com/Schneegans/Fly-Pie/blob/main/docs/dbus-interface.md#opening-menus-configured-with-the-menu-editor). Maybe right after the `ShowMenuAt` example.

2022-03-27 05:15 UTC, Schneegans commented on src/extension/Daemon.js
> +  // Opens a menu with that name if there are currently none open. Closes the currently
I think `clang-format` fails due to this trailing space here:

```suggestion
  // Opens a menu with that name if there are currently none open. Closes the currently
```

2022-03-27 05:15 UTC, Schneegans commented on src/extension/Daemon.js
> +    }
Here are two `this` missing:

```suggestion
    if (this._menu.getID() == null) {
      return this.ShowMenu(name);
    } else {
      return this.CancelMenu();
    }
```

2022-03-27 20:40 UTC, GestaltEngine commented
This should be it. Clang-format didn't like the trailing spaces indeed. 
Added a couple of lines into documentation. Maybe they would be better placed after the `CloseMenu` example, considering that it inherits the functionality from both `ShowMenu` and `CloseMenu`?

2022-03-28 13:42 UTC, GestaltEngine commented
Sorry such a small change is taking so long. I will be more thorough with future PRs.

2022-03-29 03:47 UTC, Schneegans approved these changes

2022-03-29 03:56 UTC, merged

2022-03-29 03:56 UTC, Schneegans commented
Thanks again, it looks good now! I just realized that one problem is currently that a script couldn't tell if a menu was closed or opened by the method. So after I merged it, I'll make a tiny tweak so that the method returns a negative number if it canceled a menu. 

> I will be more thorough with future PRs.

I don't mind how long or how many "revert" commits it takes as long as the result is a cool contribution! So I am definitely looking forward to to your future PRs :wink:

Thank you once more!