Add checks
Schneegans/Fly-Pie pull request #42
Opened 2020-11-17 13:16 UTC by daPhipz

See #39.

2020-11-17 13:17 UTC, daPhipz commented
Weird... It doesn't do any checks for me...

2020-11-17 14:04 UTC, daPhipz commented
Is the `script_functionality` test working correctly now? I wonder why it shows only one error message when we check whether the `gettext` package is installed or not...

I will fix the shellcheck errors next.

2020-11-17 15:16 UTC, daPhipz commented
OK, so this is as far as I get at the moment. Funnily enough, when I run `shellcheck` against `cloc.sh` locally on my machine, it doesn't throw any error at all...
I have the fear of breaking things so please check for yourself what needs to be done here.
We could of course bump up the severity level of `shellcheck` (from highest to lowest: `error`, `warning`, `info` and `style`) as well and "fix" it that way.

2020-11-19 10:18 UTC, Schneegans requested changes
Looks good! Just some minor remarks from my side. And I tested the changes ShellCheck suggests for `cloc.sh` and they seem to work.

2020-11-19 10:18 UTC, Schneegans commented on .github/workflows/checks.yml
> +  shellcheck:
```suggestion
  shellcheck:
    name: Run ShellCheck
```

2020-11-19 10:18 UTC, Schneegans commented on .github/workflows/checks.yml
> +      - name: Run shellcheck
```suggestion
      - name: Run ShellCheck
```

2020-11-19 10:18 UTC, Schneegans commented on .github/workflows/checks.yml
> +    - name: Check correct workflow # Now, gettext will be installed and both IVERTED if statements should be false.
```suggestion
    - name: Check correct workflow # Now, gettext will be installed and both INVERTED if statements should be false.
```

2020-11-19 10:18 UTC, Schneegans commented on .github/workflows/checks.yml
> +  script_functionality:
```suggestion
  script_functionality:
    name: Check Script Functionality
```

2020-11-19 10:18 UTC, Schneegans commented on CONTRIBUTING.md
> +:heavy_check_mark: `:heavy_check_mark:` | When you worked on checks or adjusted the code to be compliant with them
```suggestion
:heavy_check_mark: `:heavy_check_mark:` | When you worked on checks or adjusted the code to be compliant with them.
```

2020-11-19 18:05 UTC, Schneegans approved these changes

2020-11-19 18:06 UTC, merged