Feature/refactor menu description
Schneegans/Fly-Pie pull request #49
Opened 2020-11-29 19:06 UTC by Schneegans

This monster-pull-request addresses #37, #38, and #48. Here is the list of major changes:
* All predefined menus (`Bookmarks`, `Devices`, etc.) can now be top-level menus.
* There is no differentiation between top-level and submenus anymore. Therefore you can drag entire menus into other menus in the menu editor. Or you can make a former submenu to a top-level menu by drag'n'drop. The items `Top-Level Menu` and `Submenu` are now merged to a `Custom Menu`.
* The D-Bus interface of Fly-Pie now supports all action of menu types. You can open any menu you can configure in the menu editor also via the D-Bus interface. The README.md has been extended to contain a full description of the menu configuration format.
* The `ItemRegistry` has been refactor so that all action and menu types have their own files.

Due to all these changes, the translations need an update. Especially most mentions of "Submenu" will have to be replaced with "Menu".

2020-11-29 19:27 UTC, Schneegans commented
@daPhipz Could you have a look at the updates to the German translation (https://github.com/Schneegans/Fly-Pie/pull/49/files#diff-6686c8173bf4fa70e9c9755259206f2c5c4fa9fde6269d36e5262dcc09abcf25)? 90 % of the diff are changed line numbers, but several strings have changed and some have been added.

It would be great if you could also check the new D-Bus section of the README.md (https://github.com/Schneegans/Fly-Pie/tree/feature/refactor-menu-description#fly-pies-d-bus-interface) for any typos.

Before I merge this PR, I will try to in-depth test all features of Fly-Pie. Especially the drag'n'drop features of the menu editor have become way more complex - I am sure that there are some bugs to be found! If you have some time I would greatly appreciate it if you could test this branch! Things we could test:

- [ ] Importing menu configurations from the `develop` branch.
- [ ] Exporting and re-importing a menu configuration in this branch.
- [ ] Functionality of all actions and menus.
- [ ] Functionality of menus when added as top-level menus.
- [ ] Internal drag'n'drop in the menu. With Live-Preview, with <kbd>Ctrl</kbd> pressed, from top-level to other menus, ... 
- [ ] External drag'n'drop. Try dragging whatever to the editor :smile: 
- [ ] The D-Bus interface. For example, try to open a custom menu exported from the menu editor.
- [ ] The example commands from the README.md
- [ ] Whatever else comes to our minds...

Once it is merged, I'll create a new issue for updating the Italian translation. Then  we can proceed to release version 4 as the change log is quite substantial already. The remaining issues can be rescheduled to Fly-Pie 5.

2020-11-30 01:00 UTC, daPhipz requested changes
Wow, this review turned out much bigger than expected :joy:
README is free of typos as far as I could see :+1: 
I spotted some inconsistencies between the original strings and the german translation, please have a look at those. Where applicable, I commented in the original source code and not in the `de.po` file.

Please, do not feel offended by my somewhat cold, short comments - I simply wanted to be efficient and quick. I have friendly intentions and by no means want to criticize your awesome work! Sorry if some comments seem harsh - they are by no means intended to insult or be rude! :kissing_heart:

2020-11-30 08:34 UTC, Schneegans commented on po/de.po
> +msgstr "Deaktiviert."
I added a comment!

2020-11-30 08:34 UTC, Schneegans commented on po/de.po
> +msgstr "Diese ID wird dem D-Bus Signal übergeben."
I think it's ok without. I changed it accordingly.

2020-11-30 08:35 UTC, Schneegans commented on po/de.po
> +"Das Menü kann mit obigem Tastaturkürzel geöffnet werden. Es ist auch "
I changed the entire description a little bit to make things clearer, I hope :smile:

2020-11-30 08:35 UTC, Schneegans commented on po/de.po
> +msgstr "Häufig verwendete Anwendungen"
Done.

2020-11-30 08:35 UTC, Schneegans commented on po/de.po
> +"Das <b>Häufig-verwendete-Anwendungen</b>-Menü zeigt eine Liste oft "
Done.

2020-11-30 08:35 UTC, Schneegans commented on po/de.po
> +"zwölf beschränken."
I changed the original string.

2020-11-30 08:41 UTC, Schneegans commented
Thank you so much! This was really a lot!

2020-11-30 09:29 UTC, daPhipz commented
No problem! Happy to help :)

2020-12-01 07:53 UTC, Schneegans commented
I haven't spotted any bugs yet. So I will merge this now and create an issue for the Italian translation. If we discover any new bugs, we can create a new issue accordingly!

2020-12-01 07:53 UTC, merged